echo off
set CONFIGURATION=%1
set FILENAME=%2
set DESTINATION_PATH=..\DriversGame

echo Copying %CONFIGURATION% %FILENAME% to %DESTINATION_PATH%

copy %CONFIGURATION%\%FILENAME% %DESTINATION_PATH%\%FILENAME% /Y /V

pause