target("shinyProfiler")
    set_group("dependency")
    set_kind("static")
    setup_runtime_config()
    add_files("/src/*.c")
    add_headerfiles("include/**.h")
    add_includedirs("include/", { public = true })