//////////////////////////////////////////////////////////////////////////////////
// Copyright (C) Inspiration Byte
// 2009-2022
//////////////////////////////////////////////////////////////////////////////////
// Description: Sound emitter system
//////////////////////////////////////////////////////////////////////////////////

#pragma once
#include "audio/IEqAudioSystem.h"
#include "source/snd_source.h"
#include "eqSoundEmitterCommon.h"

/*
*
* ADVANCED SOUND SCRIPT FEATURES
*
	const "test" 1.0;

	// input NAME MIN_RANGE MAX_RANGE
	input "tractionSlide" 0.0 18.0;
	input "laterialSlide" 0.0 18.0;

	// mixer are basically functions - "add", "sub", "mul", "div", "min", "max", "average", "spline", "fade", "use"
	//	"add", "sub", "mul", "div", "min", "max" - basic functions
	//	"average" - normalized value of sum of N arguments
	//	"spline" - takes value and passes it through spline interpolation
	//	"fade" - same as "spline", but instead it's being split into multiple values (array)
	//	"use" - make a copy of value

	// each "mixer" declares a variable that can be used
	// in other mixers as an input value or as output

	mixer avgVal max tractionSlide laterialSlide;
	mixer volume spline avgVal 0.0 1.0 0.0 1.0 1.0;
	mixer pitch spline avgVal 0.0 1.0 0.0 1.0 1.0;
	mixer traction spline avgVal 0.0 1.0 1.0 1.0;
	mixer tractionSampleFade fade traction 2 0.0 1.0 1.0 1.0;
	mixer lateralSampleFade fade tractionSampleFade[1] 2 0.0 1.0 1.0 1.0;

	// svolume is individual sample volume (for each "wave")
	svolume 0 "tractionSampleFade[0]";
	svolume 1 "lateralSampleFade[0]";
	svolume 2 "lateralSampleFade[1]";

	// spitch is individual sample pitch (for each "wave")
	spitch 1 "tractionSampleFade[0]";
	spitch 2 "lateralSampleFade[0]";

	// specifying string value makes use of the mixed value or input
	volume "volume";
	pitch "pitch";
*/

struct KVSection;

static constexpr const int MAX_SOUND_SAMPLES_SCRIPT = 8;
static constexpr const uint8 SOUND_VAR_INVALID = 0xff;

enum ESoundParamType : int
{
	SOUND_PARAM_VOLUME = 0,
	SOUND_PARAM_PITCH,
	SOUND_PARAM_HPF,
	SOUND_PARAM_LPF,		// TODO: merge LPF/HPF
	SOUND_PARAM_AIRABSORPTION,
	SOUND_PARAM_ROLLOFF,
	SOUND_PARAM_ATTENUATION,
	SOUND_PARAM_SAMPLE_VOLUME,
	SOUND_PARAM_SAMPLE_PITCH,

	SOUND_PARAM_COUNT,
};

enum ESoundNodeType : int
{
	SOUND_NODE_CONST = 0,
	SOUND_NODE_INPUT,
	SOUND_NODE_FUNC,

	SOUND_NODE_TYPE_COUNT
};

enum ESoundNodeFlags : int
{
	SOUND_NODE_FLAG_AUTOGENERATED = (1 << 0),
	SOUND_NODE_FLAG_OUTPUT = (1 << 1),
};

enum ESoundFuncType : int
{
	SOUND_FUNC_COPY,
	SOUND_FUNC_ADD,
	SOUND_FUNC_SUB,
	SOUND_FUNC_MUL,
	SOUND_FUNC_DIV,
	SOUND_FUNC_MIN,
	SOUND_FUNC_MAX,
	SOUND_FUNC_ABS,
	SOUND_FUNC_AVERAGE,
	SOUND_FUNC_SPLINE,
	SOUND_FUNC_FADE,

	SOUND_FUNC_COUNT
};

enum ESoundFuncArgCount
{
	SOUND_FUNC_ARG_VARIADIC = 0x80
};

static const char* s_soundParamNames[] = {
	"volume",
	"pitch",
	"hpf",
	"lpf",
	"airAbsorption",
	"rollOff",
	"distance",
	"svolume",
	"spitch",
};
static_assert(elementsOf(s_soundParamNames) == SOUND_PARAM_COUNT, "s_soundParamNames and SOUND_PARAM_COUNT needs to be in sync");

static float s_soundParamDefaults[] = {
	1.0f,
	1.0f,
	1.0f,
	1.0f,
	0.0f,
	2.0f,
	1.0f,
	1.0f,
	1.0f,
};
static_assert(elementsOf(s_soundParamDefaults) == SOUND_PARAM_COUNT, "s_soundParamDefaults and SOUND_PARAM_COUNT needs to be in sync");

struct SoundFuncDesc
{
	EqStringRef name;
	uint8 argCount;
	uint8 retCount;
};

static SoundFuncDesc s_soundFuncTypeDesc[] = {
	{ "copy", SOUND_FUNC_ARG_VARIADIC, SOUND_FUNC_ARG_VARIADIC },
	{ "add", 2, 1 },
	{ "sub", 2, 1 },
	{ "mul", 2, 1 },
	{ "div", 2, 1 },
	{ "min", 2, 1 },
	{ "max", 2, 1 },
	{ "abs", SOUND_FUNC_ARG_VARIADIC, SOUND_FUNC_ARG_VARIADIC },
	{ "average", SOUND_FUNC_ARG_VARIADIC, 1 },
	{ "spline", 1, 1 },
	{ "fade", 1, SOUND_FUNC_ARG_VARIADIC },
};
static_assert(elementsOf(s_soundFuncTypeDesc) == SOUND_FUNC_COUNT, "s_soundFuncTypeNames and SOUND_FUNC_COUNT needs to be in sync");

struct SoundSplineDesc
{
	static constexpr const int MAX_SPLINE_POINTS = 10;
	float	values[MAX_SPLINE_POINTS * 2];
	uint8	valueCount{ 0 }; // divide by two pls

	static float splineInterpLinear(float t, int maxPoints, const float* points);
	static float splineInterp(float t, int maxPoints, const float* points);

	void	Reset();
	void	Fix();
};

struct SoundNodeDesc
{
	static constexpr int NODE_ID_BITS = 5;
	static constexpr int ARRAY_IDX_BITS = 3;

	static constexpr int MAX_SOUND_NODES = 1 << NODE_ID_BITS;
	static constexpr int MAX_ARRAY_IDX = 1 << ARRAY_IDX_BITS;

	char			name[30]{ 0 };
	uint8			type{ 0 };
	uint8			flags{ 0 };
	float			inputConst[MAX_ARRAY_IDX]{ 0.0f };

	union {
		struct {
			uint8	inputIds[MAX_ARRAY_IDX];
			uint8	type;						// ESoundFuncType
			uint8	outputCount;
			uint8	inputCount;
		} func;
		struct {
			float	rMin;
			float	rMax;
			uint8	valueCount;
		} input;
		struct {
			uint8	paramId;
			uint8	valueCount;
		} c;
	};

	static void UnpackInputIdArrIdx(uint8 inputId, uint& id, uint& arrayIdx);
	static uint8 PackInputIdArrIdx(uint id, uint arrayIdx);
};

struct SoundScriptDesc : public WeakRefObject<SoundScriptDesc>
{
	EqString				name;
	Array<ISoundSourcePtr>	samples{ PP_SL };
	Array<EqString>			soundFileNames{ PP_SL };

	Array<SoundNodeDesc>	nodeDescs{ PP_SL };
	Array<SoundSplineDesc>	splineDescs{ PP_SL };
	Map<int, int>			inputNodeMap{ PP_SL };	// maps nodeName -> nodeIdx
	uint8					paramNodeMap[SOUND_PARAM_COUNT];

	bool				loop : 1;
	bool				is2d : 1;
	bool				randomSample : 1;

	uint				sampleRandomizer{ 0 };

	int					channelType{ CHAN_INVALID };
	float				maxDistance{ 1.0f };
	float				stopLoopTime{ 0.0f };
	float				startLoopTime{ 0.0f };

	const ISoundSource* GetBestSample(int sampleId /*= -1*/);
	uint8				FindVariableIndex(const char* varName) const;
	int					GetInputNodeId(int nameHash) const;

	static void			ParseDesc(SoundScriptDesc& scriptDesc, const KVSection& scriptSection, const KVSection* defaultsSec);
	static void			ReloadDesc(SoundScriptDesc& scriptDesc, const KVSection& scriptSection);
};