//////////////////////////////////////////////////////////////////////////////////
// Copyright (C) Inspiration Byte
// 2009-2020
//////////////////////////////////////////////////////////////////////////////////
// Description: Configuration file loader
//////////////////////////////////////////////////////////////////////////////////

#include "core/core_common.h"

#include "core/IConsoleCommands.h"
#include "core/IFileSystem.h"
#include "core/ConVar.h"
#include "core/ConCommand.h"
#include "input/InputCommandBinder.h"

void WriteCfgFile(const char *pszFilename, bool bWriteKeyConfiguration /*= true*/)
{
	IFileStreamPtr cfgfile = g_fileSystem->Open(pszFilename, FS_OPEN_WRITE);
	if(!cfgfile)
	{
		MsgError("Failed to write configuraton file '%s'\n", pszFilename);
		return;
	}

	MsgInfo("Writing configuraton file '%s'\n",pszFilename);

	cfgfile->Print("// Auto-generated by WriteCfgFile()\n");

	if(bWriteKeyConfiguration)
		g_inputCommandBinder->WriteBindings(cfgfile);

	const ConCommandListRef cmdList = g_consoleCommands->GetAllCommands();

	for(ConCommandBase* cmdBase : cmdList)
	{
		if (!cmdBase->IsConVar() || !(cmdBase->GetFlags() & CV_ARCHIVE))
			continue;

		const ConVar *cv = static_cast<ConVar*>(cmdBase);

		// NOTE: commented out because config_default. Need support for it.
		// if (CString::Compare(cv->GetDefaultValue(), cv->GetString()) == 0)
		// 	continue;

		cfgfile->Print("seti %s %s\n", cv->GetName(), cv->GetString());
	}
}

DECLARE_CMD(writecfg,"Saves the confirugation file", 0)
{
	WriteCfgFile(CMD_ARGC > 0 ? CMD_ARGV(0) : "user.cfg",true);
}
