name: Linux Make

on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
      - 'premake*.lua'
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
      - 'premake*.lua'
env:
  MAKEFILE_PATH: ./build
  BUILD_CONFIGURATION: release
  BUILD_CONFIGURATION_U: Release
  BUILD_PLATFORM: x64
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONSPAT }}
        submodules: recursive
        
    - name: Setup AppImageTool
      uses: AnimMouse/setup-appimage@v1
      with:
        name: appimagetool
        url: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        
    - name: Install dependencies 1
      run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install -y build-essential libsdl2-dev libopenal-dev libxxf86vm-dev libwxgtk3.0-gtk3-dev libwxbase3.0-dev
   
    - name: Install dependencies 2
      run: ./linux_dev_prepare.sh

    - name: Generate Makefile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./premake5 --file=game/DriverSyndicate/premake5.lua gmake2
      
    - name: make
      working-directory: ${{env.MAKEFILE_PATH}}
      run: make config=${{env.BUILD_CONFIGURATION}}_${{env.BUILD_PLATFORM}} -j10
      
    - name: Create appimage
      run: .github/make_appimage.sh $PWD/game/DriverSyndicate/DrvSyn.AppDir DrvSyn_${{env.BUILD_CONFIGURATION_U}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: DrvSyn_linux_${{env.BUILD_CONFIGURATION}}_${{env.BUILD_PLATFORM}}
        path: |
          *.AppImage

#          build/bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION_U}}/*.so
#          build/bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION_U}}/DrvSyn_${{env.BUILD_CONFIGURATION_U}}
#          build/bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION_U}}/fcompress
#          build/bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION_U}}/animca
#          build/bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION_U}}/egfca
#          build/bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION_U}}/atlasgen
#          build/bin/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION_U}}/texcooker