name: Linux Make

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  BUILD_CONFIGURATION: release
  BUILD_PLATFORM: x64
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONSPAT }}
        submodules: recursive
    
    - uses: abel0b/setup-premake@v2.2
      with:
        version: "5.0.0-beta2"
        
    - name: Install dependencies
      run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install -y build-essential libsdl2-dev libopenal-dev libxxf86vm-dev libwxgtk3.0-gtk3-dev libwxbase3.0-dev
        
    - name: Generate Makefile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake5 gmake2
      
    - name: make
      working-directory: ./project_gmake2
      run: make config=${{env.BUILD_CONFIGURATION}}_${{env.BUILD_PLATFORM}} -j10
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: DrvSyn_linux_${{env.BUILD_CONFIGURATION}}_${{env.BUILD_PLATFORM}}
        path: |
          bin/x64/Release/*.so
          bin/x64/Release/DrvSyn_${{env.BUILD_CONFIGURATION}}
          bin/x64/Release/fcompress
          bin/x64/Release/animca
          bin/x64/Release/egfca
          bin/x64/Release/atlasgen
          bin/x64/Release/texcooker
