name: Linux Make

on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
      - 'premake*.lua'
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
      - 'premake*.lua'

env:
  PROJECT_NAME: DriverSyndicate
  APP_NAME: DrvSyn
  BUILD_CONFIGURATION: Retail
  BUILD_PLATFORM: x64
  
  EXE_SUFFIX:
  BUILD_CONFIGURATION_LOWER: retail


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONSPAT }}
        submodules: recursive
        
    - name: Setup AppImageTool
      uses: AnimMouse/setup-appimage@v1
      with:
        name: appimagetool
        url: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        
    - name: Install dependencies 1
      run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install -y build-essential libsdl2-dev libopenal-dev libxxf86vm-dev
   
    - name: Install dependencies 2
      run: ./linux_dev_prepare.sh

    - name: Generate Makefile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./premake5 --file=game/${{env.PROJECT_NAME}}/premake5.lua gmake2
      
    - name: make
      working-directory: ./build/${{env.PROJECT_NAME}}.solution
      run: make config=${{env.BUILD_CONFIGURATION_LOWER}}_${{env.BUILD_PLATFORM}} -j10
            
    - name: Create appimage
      run: .github/make_appimage.sh $PWD/game/${{env.PROJECT_NAME}}/${{env.APP_NAME}}.AppDir
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{env.APP_NAME}}_Linux_${{env.BUILD_CONFIGURATION}}_${{env.BUILD_PLATFORM}}
        path: |
          *.AppImage
