name: Linux Make

on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
      - 'premake*.lua'
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
      - 'premake*.lua'

env:
  PROJECT_NAME: auto_tests
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  
  EXE_SUFFIX:
  BUILD_CONFIGURATION_LOWER: retail


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONSPAT }}
        submodules: recursive
        
    - name: Setup AppImageTool
      uses: AnimMouse/setup-appimage@v1
      with:
        name: appimagetool
        url: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        
    - name: Install dependencies 1
      run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install -y build-essential libsdl2-dev libopenal-dev libxxf86vm-dev
   
    - name: Install dependencies 2
      run: ./utils/linux_dev_prepare.sh

    - name: Generate Makefile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./utils/premake5 --file=premake5-tests.lua gmake2
      
    - name: make
      working-directory: ./build/${{env.PROJECT_NAME}}.solution
      run: make config=${{env.BUILD_CONFIGURATION_LOWER}}_${{env.BUILD_PLATFORM}} -j10
            
